cinst steam -y --cacheLocation "C:\temp"
cinst epicgameslauncher -y --cacheLocation "C:\temp"
cinst origin -y --cacheLocation "C:\temp"
cinst uplay -y --cacheLocation "C:\temp"
cinst playnite -y --cacheLocation "C:\temp"
cinst discord -y --cacheLocation "C:\temp"
cinst steam-cleaner -y --cacheLocation "C:\temp"